services:
  ridewise.api:
    image: ridewiseapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"  
    depends_on:
      - postgres
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"      # Porta para a comunicação com o RabbitMQ
      - "15672:15672"    # Porta para o painel de gerenciamento do RabbitMQ
    networks:
      - ridewise_net
      
  postgres:
    container_name: "Postgres"
    image: "postgres:14.7"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=123456"
      - "POSTGRES_DB=JobService"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 10s
      retries: 10

networks:
  ridewise_net:
    driver: bridge