services:
  ridewise.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTP_PORTS=5001
    ports:
      - "5000:5000"
      - "5001:5001"
