// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ride_wise_api.Infrastructure;

#nullable disable

namespace ride_wise_api.Migrations
{
    [DbContext(typeof(RiseWiseManagerDbContext))]
    [Migration("20241003160447_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ride_wise_api.Domain.Models.DeliveryAgent", b =>
                {
                    b.Property<int>("DriverLicenseNumber")
                        .HasColumnType("integer");

                    b.Property<string>("IdentificationDocument")
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DriverLicenseImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DriverLicenseType")
                        .HasColumnType("integer");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DriverLicenseNumber", "IdentificationDocument");

                    b.HasIndex("Identification")
                        .IsUnique();

                    b.ToTable("DeliveryAgents");
                });

            modelBuilder.Entity("ride_wise_api.Domain.Models.MotorCycle", b =>
                {
                    b.Property<string>("LicensePlate")
                        .HasColumnType("text");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("LicensePlate");

                    b.HasIndex("Identification")
                        .IsUnique();

                    b.ToTable("MotorCycles");
                });

            modelBuilder.Entity("ride_wise_api.Domain.Models.Rental", b =>
                {
                    b.Property<string>("Identification")
                        .HasColumnType("text");

                    b.Property<string>("DeliveryAgentIdentification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstimatedEndDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MotorCycleIdentification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Identification");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("ride_wise_api.Domain.Models.DeliveryAgent", b =>
                {
                    b.HasOne("ride_wise_api.Domain.Models.Rental", "Rental")
                        .WithOne("DeliveryAgent")
                        .HasForeignKey("ride_wise_api.Domain.Models.DeliveryAgent", "Identification")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rental");
                });

            modelBuilder.Entity("ride_wise_api.Domain.Models.MotorCycle", b =>
                {
                    b.HasOne("ride_wise_api.Domain.Models.Rental", "Rental")
                        .WithOne("MotorCycle")
                        .HasForeignKey("ride_wise_api.Domain.Models.MotorCycle", "Identification")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rental");
                });

            modelBuilder.Entity("ride_wise_api.Domain.Models.Rental", b =>
                {
                    b.Navigation("DeliveryAgent")
                        .IsRequired();

                    b.Navigation("MotorCycle")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
